export const MAXIMUM_AUDIT_ARCHIVE_BYTES = Symbol(
  "MAXIMUM_AUDIT_ARCHIVE_BYTES",
);
export const MAXIMUM_AUDIT_ARCHIVE_EVENT_COUNT = Symbol(
  "MAXIMUM_AUDIT_ARCHIVE_EVENT_COUNT",
);
export const MAXIMUM_BACKUP_BYTES = Symbol("MAXIMUM_BACKUP_BYTES");
export const KERNEL_WORKER = Symbol("KERNEL_WORKER");
export const RESTORE_DEPLOYMENT = Symbol("RESTORE_DEPLOYMENT");
export const WORKER_CONFIGURATION = Symbol("WORKER_CONFIGURATION");
export const WORKER_JOB_LOGGER = Symbol("WORKER_JOB_LOGGER");
