export const API_CONFIGURATION = Symbol("API_CONFIGURATION");
export const AUDIT_CONFIGURATION = Symbol("AUDIT_CONFIGURATION");
export const CLOCK = Symbol("CLOCK");
export const PASSWORD_RESET_MAILER = Symbol("PASSWORD_RESET_MAILER");
export const KERNEL_RUNTIME_DEPLOYMENT_CONFIGURATION = Symbol(
  "KERNEL_RUNTIME_DEPLOYMENT_CONFIGURATION",
);
