export const API_CONFIGURATION = Symbol("API_CONFIGURATION");
export const AUDIT_CONFIGURATION = Symbol("AUDIT_CONFIGURATION");
export const CLOCK = Symbol("CLOCK");
export const OIDC_CLIENT_SECRET_RESOLVER = Symbol("OIDC_CLIENT_SECRET_RESOLVER");
export const OIDC_PROVIDER_CLIENT = Symbol("OIDC_PROVIDER_CLIENT");
export const KERNEL_RUNTIME_DEPLOYMENT_CONFIGURATION = Symbol(
  "KERNEL_RUNTIME_DEPLOYMENT_CONFIGURATION",
);
