packages:
  - "apps/*"
  - "packages/*"
engineStrict: true
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
overrides:
  '@types/node': 24.13.3
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  prisma: true
